import { TranscriptSegment } from "@prisma/client";

export const meetingTranscript:TranscriptSegment[] = [
  {
    id: "tr_001",
    meetingId: "test",
    text: "Alright, let's go through today's menu. Before service, I want to make sure everyone knows what's available, what's running low, and what we need to push today.",
    startTime: 1786698000,
    endTime: 1786698035,
    speakerId: "speaker_chef",
    words: [
      { word: "Alright,", speaker: 0 },
      { word: "let's", speaker: 0 },
      { word: "go", speaker: 0 },
      { word: "through", speaker: 0 },
      { word: "today's", speaker: 0 },
      { word: "menu.", speaker: 0 },
    ],
    createdAt: new Date("2026-08-14T09:00:35Z"),
  },
  {
    id: "tr_002",
    meetingId: "test",
    text: "The grilled salmon is fully stocked. We've got enough for around thirty covers, and the delivery this morning was good.",
    startTime: 1786698035,
    endTime: 1786698060,
    speakerId: "speaker_manager",
    words: null,
    createdAt: new Date("2026-08-14T09:01:00Z"),
  },
  {
    id: "tr_003",
    meetingId: "test",
    text: "The mushroom risotto is going ahead as today's special. The mushrooms came in fresh, we've got plenty of stock, and the kitchen can turn it around quickly during the dinner rush.",
    startTime: 1786698060,
    endTime: 1786698095,
    speakerId: "speaker_chef",
    words: [
      { word: "The", speaker: 0 },
      { word: "mushroom", speaker: 0 },
      { word: "risotto", speaker: 0 },
      { word: "is", speaker: 0 },
      { word: "going", speaker: 0 },
      { word: "ahead.", speaker: 0 },
    ],
    createdAt: new Date("2026-08-14T09:01:35Z"),
  },
  {
    id: "tr_004",
    meetingId: "test",
    text: "Why are we pushing the risotto instead of the pasta special?",
    startTime: 1786698095,
    endTime: 1786698110,
    speakerId: "speaker_server",
    words: [
      { word: "Why", speaker: 2 },
      { word: "are", speaker: 2 },
      { word: "we", speaker: 2 },
      { word: "pushing", speaker: 2 },
      { word: "the", speaker: 2 },
      { word: "risotto?", speaker: 2 },
    ],
    createdAt: new Date("2026-08-14T09:01:50Z"),
  },
  {
    id: "tr_005",
    meetingId: "test",
    text: "The pasta is good, but we're low on the fresh pasta sheets and won't get another delivery until tomorrow. The risotto makes more sense today because we have the ingredients and the margins are better.",
    startTime: 1786698110,
    endTime: 1786698145,
    speakerId: "speaker_manager",
    words: [
      { word: "The", speaker: 1 },
      { word: "pasta", speaker: 1 },
      { word: "is", speaker: 1 },
      { word: "good,", speaker: 1 },
      { word: "but", speaker: 1 },
      { word: "we're", speaker: 1 },
      { word: "low.", speaker: 1 },
    ],
    createdAt: new Date("2026-08-14T09:02:25Z"),
  },
  {
    id: "tr_006",
    meetingId: "test",
    text: "Any allergy concerns with the risotto?",
    startTime: 1786698145,
    endTime: 1786698155,
    speakerId: "speaker_server",
    words: [
      { word: "Any", speaker: 2 },
      { word: "allergy", speaker: 2 },
      { word: "concerns", speaker: 2 },
      { word: "with", speaker: 2 },
      { word: "the", speaker: 2 },
      { word: "risotto?", speaker: 2 },
    ],
    createdAt: new Date("2026-08-14T09:02:35Z"),
  },
  {
    id: "tr_007",
    meetingId: "test",
    text: "The standard version contains dairy because we finish it with parmesan and butter. We can make a dairy-free version, but the server needs to clearly flag the allergy so the kitchen uses a clean pan and separate utensils.",
    startTime: 1786698155,
    endTime: 1786698195,
    speakerId: "speaker_chef",
    words: [
      { word: "The", speaker: 0 },
      { word: "standard", speaker: 0 },
      { word: "version", speaker: 0 },
      { word: "contains", speaker: 0 },
      { word: "dairy.", speaker: 0 },
    ],
    createdAt: new Date("2026-08-14T09:03:15Z"),
  },
  {
    id: "tr_008",
    meetingId: "test",
    text: "We also have two guests on holdia tonight, table twelve and table eighteen. Both reservations have allergy notes, so please double-check those before service.",
    startTime: 1786698195,
    endTime: 1786698225,
    speakerId: "speaker_manager",
    words: [
      { word: "We", speaker: 1 },
      { word: "also", speaker: 1 },
      { word: "have", speaker: 1 },
      { word: "two", speaker: 1 },
      { word: "guests.", speaker: 1 },
    ],
    createdAt: new Date("2026-08-14T09:03:45Z"),
  },
  {
    id: "tr_009",
    meetingId: "test",
    text: "We're also nearly out of chicken stock. There's maybe enough for eight more portions. Don't use it for staff meals; we need it for the soup and the chicken dish.",
    startTime: 1786698225,
    endTime: 1786698260,
    speakerId: "speaker_chef",
    words: [
      { word: "We're", speaker: 0 },
      { word: "also", speaker: 0 },
      { word: "nearly", speaker: 0 },
      { word: "out", speaker: 0 },
      { word: "of", speaker: 0 },
      { word: "chicken", speaker: 0 },
      { word: "stock.", speaker: 0 },
    ],
    createdAt: new Date("2026-08-14T09:04:20Z"),
  },
  {
    id: "tr_010",
    meetingId: "test",
    text: "What's happening with the leak in the kitchen?",
    startTime: 1786698260,
    endTime: 1786698270,
    speakerId: "speaker_manager",
    words: [
      { word: "What's", speaker: 1 },
      { word: "happening", speaker: 1 },
      { word: "with", speaker: 1 },
      { word: "the", speaker: 1 },
      { word: "leak?", speaker: 1 },
    ],
    createdAt: new Date("2026-08-14T09:04:30Z"),
  },
  {
    id: "tr_011",
    meetingId: "test",
    text: "There's still a small leak underneath the prep sink. Maintenance checked it yesterday but the replacement valve hasn't arrived yet. Put a bucket underneath it and keep the area dry because I don't want anyone slipping.",
    startTime: 1786698270,
    endTime: 1786698310,
    speakerId: "speaker_chef",
    words: [
      { word: "There's", speaker: 0 },
      { word: "still", speaker: 0 },
      { word: "a", speaker: 0 },
      { word: "small", speaker: 0 },
      { word: "leak.", speaker: 0 },
    ],
    createdAt: new Date("2026-08-14T09:05:10Z"),
  },
  {
    id: "tr_012",
    meetingId: "test",
    text: "Are we still serving the seafood pasta today?",
    startTime: 1786698310,
    endTime: 1786698320,
    speakerId: "speaker_server",
    words: [
      { word: "Are", speaker: 2 },
      { word: "we", speaker: 2 },
      { word: "still", speaker: 2 },
      { word: "serving", speaker: 2 },
      { word: "seafood", speaker: 2 },
      { word: "pasta?", speaker: 2 },
    ],
    createdAt: new Date("2026-08-14T09:05:20Z"),
  },
  {
    id: "tr_013",
    meetingId: "test",
    text: "Yes, but only until we run out of prawns. We have enough for about fifteen portions. Once they're gone, mark the dish unavailable rather than substituting ingredients without checking with the chef.",
    startTime: 1786698320,
    endTime: 1786698360,
    speakerId: "speaker_chef",
    words: [
      { word: "Yes,", speaker: 0 },
      { word: "but", speaker: 0 },
      { word: "only", speaker: 0 },
      { word: "until", speaker: 0 },
      { word: "we", speaker: 0 },
      { word: "run", speaker: 0 },
      { word: "out", speaker: 0 },
      { word: "of", speaker: 0 },
      { word: "prawns.", speaker: 0 },
    ],
    createdAt: new Date("2026-08-14T09:06:00Z"),
  },
  {
    id: "tr_014",
    meetingId: "test",
    text: "The risotto is the main dish I want everyone recommending today. It's fresh, we have strong stock levels, the preparation time is predictable, and it gives us a good way to use the mushrooms before tomorrow's delivery.",
    startTime: 1786698360,
    endTime: 1786698400,
    speakerId: "speaker_manager",
    words: [
      { word: "The", speaker: 1 },
      { word: "risotto", speaker: 1 },
      { word: "is", speaker: 1 },
      { word: "the", speaker: 1 },
      { word: "main", speaker: 1 },
      { word: "dish.", speaker: 1 },
    ],
    createdAt: new Date("2026-08-14T09:06:40Z"),
  },
  {
    id: "tr_015",
    meetingId: "test",
    text: "Okay, I'll update the front-of-house team. We'll push the risotto, flag the allergy notes, and stop selling the seafood pasta once the prawns are gone.",
    startTime: 1786698400,
    endTime: 1786698430,
    speakerId: "speaker_server",
    words: [
      { word: "Okay,", speaker: 2 },
      { word: "I'll", speaker: 2 },
      { word: "update", speaker: 2 },
      { word: "the", speaker: 2 },
      { word: "team.", speaker: 2 },
    ],
    createdAt: new Date("2026-08-14T09:07:10Z"),
  },
];
